<a href="https://colab.research.google.com/github/Mitesh1809/CE-888/blob/main/NuralN_W.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

from scipy.io import loadmat

In [2]:
j = loadmat('WLDataAll.mat')
j

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Tue Jun  1 17:11:20 2021',
 '__version__': '1.0',
 'data': array([[[ 4.8829541e+00,  9.8011837e+00, -6.1279667e+01, ...,
          -2.3868773e+01,  1.0183847e+01,  6.5834889e+00],
         [ 1.5645766e+01,  9.2562323e+00, -5.9352314e+01, ...,
           6.3903937e+00, -3.4080923e-01,  7.2190175e+00],
         [ 1.8576738e+01,  9.6379747e+00, -5.8535995e+01, ...,
           3.4576672e+01, -3.2299006e+00,  4.3821239e-01],
         ...,
         [ 1.3261520e+01, -4.5882652e+01,  1.3235929e+01, ...,
           1.9744860e+01, -1.1103893e+01,  5.8311663e+00],
         [ 1.2880102e+01, -5.4907242e+01,  1.1796134e+01, ...,
           2.2629681e+01, -7.8801956e+00,  9.1314917e+00],
         [ 1.1365375e+01, -6.0526150e+01,  8.0718441e+00, ...,
           1.9972019e+01, -9.1800272e-02,  2.4537776e+00]],
 
        [[ 6.2141876e+00,  2.3298359e+01, -4.9112263e+01, ...,
          -2.7136732e+01,  1.3108792e+01, 

In [3]:
x = j['data']
y = j['label']

In [4]:
x

array([[[ 4.8829541e+00,  9.8011837e+00, -6.1279667e+01, ...,
         -2.3868773e+01,  1.0183847e+01,  6.5834889e+00],
        [ 1.5645766e+01,  9.2562323e+00, -5.9352314e+01, ...,
          6.3903937e+00, -3.4080923e-01,  7.2190175e+00],
        [ 1.8576738e+01,  9.6379747e+00, -5.8535995e+01, ...,
          3.4576672e+01, -3.2299006e+00,  4.3821239e-01],
        ...,
        [ 1.3261520e+01, -4.5882652e+01,  1.3235929e+01, ...,
          1.9744860e+01, -1.1103893e+01,  5.8311663e+00],
        [ 1.2880102e+01, -5.4907242e+01,  1.1796134e+01, ...,
          2.2629681e+01, -7.8801956e+00,  9.1314917e+00],
        [ 1.1365375e+01, -6.0526150e+01,  8.0718441e+00, ...,
          1.9972019e+01, -9.1800272e-02,  2.4537776e+00]],

       [[ 6.2141876e+00,  2.3298359e+01, -4.9112263e+01, ...,
         -2.7136732e+01,  1.3108792e+01, -1.0402801e-02],
        [ 2.0816244e+01,  2.2637253e+01, -4.7099533e+01, ...,
          2.6988206e+00,  1.7181083e+00,  4.6453357e-01],
        [ 2.5134890e+01, 

In [5]:
y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [6]:
y = y-1

In [7]:
x.shape, y.shape

((62, 512, 360), (1, 360))

In [8]:
x = x.T
y = y.T
x.shape, y.shape

((360, 512, 62), (360, 1))

In [9]:
x = x.reshape(x.shape[0], x.shape[1]*x.shape[2])

In [10]:
x

array([[ 4.8829541e+00,  6.2141876e+00,  5.8859887e+00, ...,
         7.3389955e+00,  1.1654859e+00,  8.4466515e+00],
       [ 9.8011837e+00,  2.3298359e+01,  2.4068096e+01, ...,
        -1.9394279e+01, -2.7115149e+01, -2.0668167e+01],
       [-6.1279667e+01, -4.9112263e+01, -1.8423073e+01, ...,
         4.2824917e+00, -1.9103953e+00, -1.5813452e+00],
       ...,
       [-2.3868773e+01, -2.7136732e+01, -3.5179005e+01, ...,
        -8.1219833e+01,  1.5229993e+01, -1.4594034e+01],
       [ 1.0183847e+01,  1.3108792e+01,  1.5467652e+01, ...,
        -1.5925308e+02, -2.6415169e+00, -5.1202698e+01],
       [ 6.5834889e+00, -1.0402801e-02, -4.1439157e+00, ...,
        -6.4565331e+01,  7.5060105e+00, -1.8992659e+01]], dtype=float32)

In [11]:
def initialize_parameters(n_in, n_out):
    
    params = dict() 
    params['W'] = np.random.randn(n_out, n_in) *0.01
    params['b'] = np.zeros((n_out, 1))

    return params

class LinearLayer:
    def __init__(self, input_shape, n_out):        
        self.m = input_shape[1]
        self.params = initialize_parameters(input_shape[0], n_out)
        self.Z = np.zeros((self.params['W'].shape[0], input_shape[1]))

    def forward(self, A_prev):
        
        self.A_prev = A_prev 
        self.Z = np.dot(self.params['W'], self.A_prev) + self.params['b'] 

    def backward(self, upstream_grad):
        self.dW = np.dot(upstream_grad, self.A_prev.T)
        self.db = np.sum(upstream_grad, axis=1, keepdims=True)
        self.dA_prev = np.dot(self.params['W'].T, upstream_grad)

    def update_params(self, learning_rate=0.1):
        self.params['W'] = self.params['W'] - learning_rate * self.dW 
        self.params['b'] = self.params['b'] - learning_rate * self.db

In [12]:
class SigmoidLayer:
    
    def __init__(self, shape):
        self.A = np.zeros(shape) 

    def forward(self, Z):
        self.A = 1 / (1 + np.exp(-Z))
        
    def backward(self, upstream_grad):
        self.dZ = upstream_grad * self.A*(1-self.A)

In [13]:
def compute_stable_bce_cost(Y, Z):
  m = Y.shape[1]
  cost = (1/m) * np.sum(np.maximum(Z, 0) - Z*Y + np.log(1+ np.exp(- np.abs(Z))))
  dZ_last = (1/m) * ((1/(1+np.exp(- Z))) - Y)
  return cost, dZ_last

In [14]:
def compute_keras_like_bce_cost(Y, P_hat, from_logits=False):
    if from_logits:
        return compute_stable_bce_cost(Y, Z=P_hat)
    else:
        EPSILON = 1e-07
        P_MAX = 1- EPSILON 

        P_hat = np.clip(P_hat, a_min=EPSILON, a_max=P_MAX)
        Z = np.log(P_hat/(1-P_hat))
        return compute_stable_bce_cost(Y, Z)

In [15]:
def predict(X, Y, Zs, As, thresh=0.5):
    m = X.shape[1]
    n = len(Zs)  # number of layers in the neural network
    p = np.zeros((1, m))

    # Forward propagation
    Zs[0].forward(X)
    As[0].forward(Zs[0].Z)
    for i in range(1, n):
        Zs[i].forward(As[i-1].A)
        As[i].forward(Zs[i].Z)
    probas = As[n-1].A

    # convert probas to 0/1 predictions
    for i in range(0, probas.shape[1]):
        if probas[0, i] >= thresh:  # 0.5  the default threshold
            p[0, i] = 1
        else:
            p[0, i] = 0

    accuracy = np.sum((p == Y) / m)

    return p, probas, accuracy*100

In [16]:
from sklearn.model_selection import KFold

accuracy = []

kf = KFold(n_splits=5)
for train_index, test_index in kf.split(x):
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

    learning_rate = 1
    number_of_epochs = 30

    np.random.seed(0)
    Z1 = LinearLayer(input_shape=X_train.T.shape, n_out=1)
    A1 = SigmoidLayer(Z1.Z.shape)

    costs = [] 
    for epoch in range(number_of_epochs):
      Z1.forward(X_train.T)
      A1.forward(Z1.Z)
      cost, dZ1 = compute_stable_bce_cost(y_train.T, Z1.Z)
      if (epoch % 2) == 0 or epoch == number_of_epochs - 1:
        print("Cost at epoch#{}: {}".format(epoch, cost))
        costs.append(cost)
        Z1.backward(dZ1)
        Z1.update_params(learning_rate=learning_rate)

    predicted_outputs, p_hat, acc = predict(X=X_test.T, Y=y_test.T, 
                                                Zs=[Z1], As=[A1], thresh=0.5)
    accuracy.append(acc)
    print("\nThe accuracy of the model is: {}%".format(acc))

print(f'average accuracy: {np.mean(accuracy)}')

Cost at epoch#0: 14.45943267461816
Cost at epoch#2: 26310.081669807245
Cost at epoch#4: 11227.509671544274


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in exp
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.


Cost at epoch#6: 8735.146365628047
Cost at epoch#8: 8006.10009600604
Cost at epoch#10: 6230.751727960541
Cost at epoch#12: 3360.9439262256715
Cost at epoch#14: 1351.865098957082
Cost at epoch#16: 913.3804889852577
Cost at epoch#18: 510.34027975205225
Cost at epoch#20: 373.72416493920014
Cost at epoch#22: 962.1698543490902
Cost at epoch#24: 695.9969012143167
Cost at epoch#26: 312.7753431672738
Cost at epoch#28: 22.181377800936236
Cost at epoch#29: 3.8030119255835437

The accuracy of the model is: 38.88888888888889%
Cost at epoch#0: 13.092687900761767
Cost at epoch#2: 26991.394981977763
Cost at epoch#4: 8511.100766018588
Cost at epoch#6: 11328.274937972128
Cost at epoch#8: 6906.098752364958
Cost at epoch#10: 7821.235972052137
Cost at epoch#12: 4764.808323370275
Cost at epoch#14: 4448.124583072122
Cost at epoch#16: 4476.282664921823
Cost at epoch#18: 2553.356129513303
Cost at epoch#20: 3398.437267241679
Cost at epoch#22: 1652.2190133683607
Cost at epoch#24: 1345.3436552914272
Cost at epoc

In [17]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.losses import sparse_categorical_crossentropy
from keras.optimizers import Adam
from sklearn.model_selection import KFold
import numpy as np

kfold = KFold(n_splits=6)
fold_no = 1
acc_per_fold = list()
loss_per_fold = list()

for train, test in kfold.split(x):
    model = Sequential()
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.7))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(1, activation='softmax'))

    model.compile(loss='binary_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])

    print(f'Training for fold {fold_no} ...')
    x_train = x[train]
    y_train = y[train]
    x_test = x[test]
    y_test = y[test]


    history = model.fit(x_train, y_train,
              batch_size=20,
              epochs=10)

    # Generate generalization metrics
    scores = model.evaluate(x_test, y_test, verbose=0)
    print(f'Score for fold {fold_no}: {model.metrics_names[0]} of {scores[0]}; {model.metrics_names[1]} of {scores[1]*100}%')
    acc_per_fold.append(scores[1] * 100)
    loss_per_fold.append(scores[0])

    # Increase fold number
    fold_no = fold_no + 1

Training for fold 1 ...
Epoch 1/10
15/15 [==============================] - 22s 24ms/step - loss: 36.8221 - accuracy: 0.6191
Epoch 2/10
15/15 [==============================] - 0s 23ms/step - loss: 67.9084 - accuracy: 0.6114
Epoch 3/10
15/15 [==============================] - 0s 23ms/step - loss: 41.4823 - accuracy: 0.6277
Epoch 4/10
15/15 [==============================] - 0s 23ms/step - loss: 71.2938 - accuracy: 0.5881
Epoch 5/10
15/15 [==============================] - 0s 24ms/step - loss: 68.5464 - accuracy: 0.6230
Epoch 6/10
15/15 [==============================] - 0s 23ms/step - loss: 60.3201 - accuracy: 0.6216
Epoch 7/10
15/15 [==============================] - 0s 23ms/step - loss: 44.3339 - accuracy: 0.6114
Epoch 8/10
15/15 [==============================] - 0s 23ms/step - loss: 57.4328 - accuracy: 0.5881
Epoch 9/10
15/15 [==============================] - 0s 24ms/step - loss: 71.6127 - accuracy: 0.6047
Epoch 10/10
15/15 [==============================] - 0s 23ms/step - loss: 4